services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=db;Port=5432;Database=SuscripcionesYContratos;Username=postgres;Password=3541079;Include Error Detail=true"
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: SuscripcionesYContratos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3541079
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: