// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SuscripcionesYContratos.Infraestructura.Persistencia.ModeloPersistencia;

#nullable disable

namespace SuscripcionesYContratos.Infraestructura.Migrations
{
    [DbContext(typeof(PersistenceDbContext))]
    [Migration("20260301005309_InitialStructure")]
    partial class InitialStructure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SuscripcionesYContratos.Infraestructura.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("eventname");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOnUtc");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("SuscripcionesYContratos.Infraestructura.Persistencia.ModeloPersistencia.EFCoreEntities.CalendarioEntregaPersistenceModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<Guid>("contratoId")
                        .HasColumnType("uuid")
                        .HasColumnName("contratoId");

                    b.Property<int>("estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<TimeOnly>("hora")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora");

                    b.Property<DateTime?>("updateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updateAt");

                    b.HasKey("Id");

                    b.HasIndex("contratoId");

                    b.ToTable("CalendarioEntrega");
                });

            modelBuilder.Entity("SuscripcionesYContratos.Infraestructura.Persistencia.ModeloPersistencia.EFCoreEntities.ContratosPersistenceModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<int>("cantidadEntregas")
                        .HasColumnType("integer")
                        .HasColumnName("cantidadEntregas");

                    b.Property<int>("estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("fin")
                        .HasColumnType("date")
                        .HasColumnName("fin");

                    b.Property<TimeOnly>("hora")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora");

                    b.Property<bool>("incluyeFinDeSemana")
                        .HasColumnType("boolean")
                        .HasColumnName("incluyeFinDeSemana");

                    b.Property<DateOnly>("inicio")
                        .HasColumnType("date")
                        .HasColumnName("inicio");

                    b.Property<Guid>("pacienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("pacienteId");

                    b.Property<Guid>("planId")
                        .HasColumnType("uuid")
                        .HasColumnName("planId");

                    b.Property<int>("politicaCancelacionDias")
                        .HasColumnType("integer")
                        .HasColumnName("politicaCancelacionDias");

                    b.Property<decimal>("precioTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("precioTotal");

                    b.Property<Guid>("suscripcionId")
                        .HasColumnType("uuid")
                        .HasColumnName("suscripcionId");

                    b.Property<DateTime?>("updateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updateAt");

                    b.HasKey("Id");

                    b.HasIndex("suscripcionId");

                    b.ToTable("Contratos");
                });

            modelBuilder.Entity("SuscripcionesYContratos.Infraestructura.Persistencia.ModeloPersistencia.EFCoreEntities.SuscripcionesPersistenceModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<int>("cantidadDias")
                        .HasColumnType("integer")
                        .HasColumnName("cantidadDias");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<decimal>("precioDia")
                        .HasColumnType("numeric")
                        .HasColumnName("precioDia");

                    b.Property<DateTime?>("updateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updateAt");

                    b.HasKey("Id");

                    b.ToTable("Suscripciones");
                });

            modelBuilder.Entity("SuscripcionesYContratos.Infraestructura.Persistencia.ModeloPersistencia.EFCoreEntities.CalendarioEntregaPersistenceModel", b =>
                {
                    b.HasOne("SuscripcionesYContratos.Infraestructura.Persistencia.ModeloPersistencia.EFCoreEntities.ContratosPersistenceModel", "Contrato")
                        .WithMany("CalendarioEntregas")
                        .HasForeignKey("contratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contrato");
                });

            modelBuilder.Entity("SuscripcionesYContratos.Infraestructura.Persistencia.ModeloPersistencia.EFCoreEntities.ContratosPersistenceModel", b =>
                {
                    b.HasOne("SuscripcionesYContratos.Infraestructura.Persistencia.ModeloPersistencia.EFCoreEntities.SuscripcionesPersistenceModel", "Suscripcion")
                        .WithMany()
                        .HasForeignKey("suscripcionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Suscripcion");
                });

            modelBuilder.Entity("SuscripcionesYContratos.Infraestructura.Persistencia.ModeloPersistencia.EFCoreEntities.ContratosPersistenceModel", b =>
                {
                    b.Navigation("CalendarioEntregas");
                });
#pragma warning restore 612, 618
        }
    }
}
