// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SuscripcionesYContratos.Infraestructura.Persistencia.ModeloPersistencia;

#nullable disable

namespace SuscripcionesYContratos.Infraestructura.Migrations
{
    [DbContext(typeof(PersistenceDbContext))]
    [Migration("20260225013820_AddOutboxMessage")]
    partial class AddOutboxMessage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SuscripcionesYContratos.Dominio.Contrato.Contratos", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("estado")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("fin")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("hora")
                        .HasColumnType("time without time zone");

                    b.Property<DateOnly>("inicio")
                        .HasColumnType("date");

                    b.Property<Guid>("pacienteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("planId")
                        .HasColumnType("uuid");

                    b.Property<int>("politicaCancelacionDias")
                        .HasColumnType("integer");

                    b.Property<Guid>("suscripcionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("updateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Contratos");
                });

            modelBuilder.Entity("SuscripcionesYContratos.Dominio.Entregas.CalendarioEntrega", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("contratoId")
                        .HasColumnType("uuid");

                    b.Property<int>("estado")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("fecha")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("hora")
                        .HasColumnType("time without time zone");

                    b.Property<DateTime?>("updateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Entregas");
                });

            modelBuilder.Entity("SuscripcionesYContratos.Dominio.Suscripcion.Suscripciones", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("cantidadEntregas")
                        .HasColumnType("integer");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("incluyeFinDeSemana")
                        .HasColumnType("boolean");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("precio")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("updateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Suscripciones");
                });

            modelBuilder.Entity("SuscripcionesYContratos.Infraestructura.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOnUtc");

                    b.ToTable("OutboxMessages", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
