#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

set -e

echo "[pre-commit] dotnet format (verify)"
dotnet format --verify-no-changes

echo "[pre-commit] dotnet test"
dotnet test --configuration Release